<?php

namespace App\Providers;

use Illuminate\Cache\RateLimiting\Limit;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\RateLimiter;
use Illuminate\Support\Facades\URL;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     */
    public function register(): void
    {
        //
    }

    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        /*
        |--------------------------------------------------------------------------
        | Application URL
        |--------------------------------------------------------------------------
        |
        | Make sure URLs generated by Laravel, including email verification
        | links, use the application's configured APP_URL.
        |
        */
        URL::forceRootUrl(config('app.url'));

        RateLimiter::for('login', function (Request $request) {
            return Limit::perMinute(5)
                ->by(
                    strtolower((string) $request->input('email'))
                    . '|'
                    . $request->ip()
                );
        });

        RateLimiter::for('register', function (Request $request) {
            return Limit::perMinute(5)
                ->by($request->ip());
        });

        RateLimiter::for('verification', function (Request $request) {
            return Limit::perMinute(5)
                ->by(
                    strtolower((string) $request->input('email'))
                    . '|'
                    . $request->ip()
                );
        });
    }
}

